import Head from 'next/head'
import Image from 'next/image'
import Monopoly from '../components/Monopoly'
import styles from '../styles/Home.module.css'
import monopoly from '../public/title.png'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Monopoly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex h-screen items-center justify-center'>
        <div className='flex flex-col items-center justify-center'>
        <Image src={monopoly} width={620} height={200} alt='monopoly'/>
        <div className='flex w-full h-full items-center justify-center'>
          {/* <Counter /> */}
          <Monopoly/>
        </div>
        </div>
      </main>
    </div>
  )
}
