import Head from 'next/head'
import Image from 'next/image'
import Monopoly from '../components/Monopoly'
import styles from '../styles/Home.module.css'
import monopoly from '../public/title.png'
import Dices from '../components/Dices'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Monopoly</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex h-screen items-center justify-center'>
        <div className='flex flex-col items-center justify-center'>
          <Image src={monopoly} width={620} height={200} alt='monopoly' />
          <div className='flex w-screen'>
            <div className=' flex items-center w-1/4 justify-center'>
              <Dices />
            </div>

            <div className='flex w-1/2 h-full items-center justify-center'>
              <Monopoly />
              {/* <Counter /> */}
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
